import type {
  SpecificationEntity,
  HistoricalRecord,
  ValidationCriterion,
  ValidationResult,
  SpecificationVersion,
  SpecificationPackage,
} from './types'

// ── Entidades del modelo canónico ──────────────────────────────────────────

export const SPECIFICATION_ENTITIES: SpecificationEntity[] = [
  {
    id: 'ENT-001',
    name: 'TENANT',
    tableName: 'TENANT',
    description: 'Entidad raíz que representa cada cooperativa o entidad financiera en el sistema multi-tenant',
    status: 'VALIDADO',
    lastValidated: '2024-06-15T10:30:00Z',
    validatedBy: 'admin@cygnus.com',
    attributes: [
      { name: 'id', type: 'uuid', nullable: false, isPrimaryKey: true, isForeignKey: false, description: 'Identificador único del tenant' },
      { name: 'code', type: 'varchar(50)', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Código único del tenant (ej: CACSA)' },
      { name: 'name', type: 'varchar(100)', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Nombre completo del tenant' },
      { name: 'status', type: 'varchar(20)', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Estado del tenant (ACTIVO/INACTIVO)' },
      { name: 'created_at', type: 'timestamp', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Fecha de creación' },
      { name: 'updated_at', type: 'timestamp', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Fecha de última actualización' },
    ],
    relationships: [],
    constraints: [
      { type: 'PK', name: 'pk_tenant', columns: ['id'] },
      { type: 'UK', name: 'uk_tenant_code', columns: ['code'] },
    ],
  },
  {
    id: 'ENT-002',
    name: 'BUSINESS_PERSON',
    tableName: 'BUSINESS_PERSON',
    description: 'Personas de negocio asociadas a cada tenant, incluyendo datos de trazabilidad del sistema origen',
    status: 'VALIDADO',
    lastValidated: '2024-06-15T10:35:00Z',
    validatedBy: 'admin@cygnus.com',
    attributes: [
      { name: 'id', type: 'uuid', nullable: false, isPrimaryKey: true, isForeignKey: false, description: 'Identificador único de la persona' },
      { name: 'tenant_id', type: 'uuid', nullable: false, isPrimaryKey: false, isForeignKey: true, foreignTable: 'TENANT', description: 'FK al tenant propietario' },
      { name: 'person_type', type: 'varchar(20)', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Tipo de persona (NATURAL/JURIDICA)' },
      { name: 'identification_type', type: 'varchar(20)', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Tipo de identificación (CC/NIT/CE)' },
      { name: 'identification_number', type: 'varchar(50)', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Número de identificación único por tenant' },
      { name: 'full_name', type: 'varchar(200)', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Nombre completo o razón social' },
      { name: 'email', type: 'varchar(100)', nullable: true, isPrimaryKey: false, isForeignKey: false, description: 'Correo electrónico de contacto' },
      { name: 'phone', type: 'varchar(20)', nullable: true, isPrimaryKey: false, isForeignKey: false, description: 'Teléfono de contacto' },
      { name: 'source_system', type: 'varchar(50)', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Sistema de origen (CACSA, COOPEAGRO)' },
      { name: 'source_table', type: 'varchar(50)', nullable: true, isPrimaryKey: false, isForeignKey: false, description: 'Tabla de origen en el sistema legacy' },
      { name: 'source_person_code', type: 'varchar(100)', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Código de persona en sistema origen' },
      { name: 'source_payload', type: 'jsonb', nullable: true, isPrimaryKey: false, isForeignKey: false, description: 'Payload JSON completo del sistema origen' },
      { name: 'created_at', type: 'timestamp', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Fecha de creación' },
      { name: 'updated_at', type: 'timestamp', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Fecha de última actualización' },
      { name: 'created_by', type: 'varchar(100)', nullable: true, isPrimaryKey: false, isForeignKey: false, description: 'Usuario que creó el registro' },
      { name: 'updated_by', type: 'varchar(100)', nullable: true, isPrimaryKey: false, isForeignKey: false, description: 'Usuario que actualizó el registro' },
    ],
    relationships: [
      { targetEntity: 'TENANT', type: 'N:1', foreignKey: 'tenant_id', description: 'Cada persona pertenece a un tenant' },
      { targetEntity: 'PRODUCT', type: '1:N', foreignKey: 'primary_person_id', description: 'Una persona puede ser titular de múltiples productos' },
    ],
    constraints: [
      { type: 'PK', name: 'pk_business_person', columns: ['id'] },
      { type: 'FK', name: 'fk_person_tenant', columns: ['tenant_id'], definition: 'REFERENCES TENANT(id)' },
      { type: 'UK', name: 'uk_person_tenant_id', columns: ['tenant_id', 'identification_number'] },
    ],
  },
  {
    id: 'ENT-003',
    name: 'PRODUCT_TYPE',
    tableName: 'PRODUCT_TYPE',
    description: 'Catálogo de tipos de producto financiero por tenant, con trazabilidad al sistema origen',
    status: 'VALIDADO',
    lastValidated: '2024-06-15T10:40:00Z',
    validatedBy: 'admin@cygnus.com',
    attributes: [
      { name: 'id', type: 'uuid', nullable: false, isPrimaryKey: true, isForeignKey: false, description: 'Identificador único del tipo de producto' },
      { name: 'tenant_id', type: 'uuid', nullable: false, isPrimaryKey: false, isForeignKey: true, foreignTable: 'TENANT', description: 'FK al tenant propietario' },
      { name: 'family', type: 'varchar(50)', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Familia del producto (AHORRO, CREDITO, APORTE)' },
      { name: 'code', type: 'varchar(50)', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Código del tipo de producto' },
      { name: 'description', type: 'varchar(200)', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Descripción del tipo de producto' },
      { name: 'source_type_code', type: 'varchar(50)', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Código de tipo en sistema origen' },
      { name: 'source_line_code', type: 'varchar(50)', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Código de línea en sistema origen' },
      { name: 'created_at', type: 'timestamp', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Fecha de creación' },
      { name: 'updated_at', type: 'timestamp', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Fecha de última actualización' },
    ],
    relationships: [
      { targetEntity: 'TENANT', type: 'N:1', foreignKey: 'tenant_id', description: 'Cada tipo pertenece a un tenant' },
      { targetEntity: 'PRODUCT', type: '1:N', foreignKey: 'product_type_id', description: 'Un tipo puede clasificar múltiples productos' },
    ],
    constraints: [
      { type: 'PK', name: 'pk_product_type', columns: ['id'] },
      { type: 'FK', name: 'fk_type_tenant', columns: ['tenant_id'], definition: 'REFERENCES TENANT(id)' },
      { type: 'UK', name: 'uk_type_tenant_family_code', columns: ['tenant_id', 'family', 'code'] },
    ],
  },
  {
    id: 'ENT-004',
    name: 'PRODUCT',
    tableName: 'PRODUCT',
    description: 'Productos financieros asociados a personas y tipos de producto, con datos de trazabilidad',
    status: 'VALIDADO',
    lastValidated: '2024-06-15T10:45:00Z',
    validatedBy: 'admin@cygnus.com',
    attributes: [
      { name: 'id', type: 'uuid', nullable: false, isPrimaryKey: true, isForeignKey: false, description: 'Identificador único del producto' },
      { name: 'tenant_id', type: 'uuid', nullable: false, isPrimaryKey: false, isForeignKey: true, foreignTable: 'TENANT', description: 'FK al tenant propietario' },
      { name: 'product_type_id', type: 'uuid', nullable: false, isPrimaryKey: false, isForeignKey: true, foreignTable: 'PRODUCT_TYPE', description: 'FK al tipo de producto' },
      { name: 'primary_person_id', type: 'uuid', nullable: false, isPrimaryKey: false, isForeignKey: true, foreignTable: 'BUSINESS_PERSON', description: 'FK al titular principal' },
      { name: 'product_number', type: 'varchar(50)', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Número único del producto por tenant' },
      { name: 'status', type: 'varchar(20)', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Estado del producto (ABIERTO/CERRADO/SUSPENDIDO)' },
      { name: 'open_date', type: 'date', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Fecha de apertura del producto' },
      { name: 'close_date', type: 'date', nullable: true, isPrimaryKey: false, isForeignKey: false, description: 'Fecha de cierre (null si está abierto)' },
      { name: 'currency_code', type: 'varchar(3)', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Código de moneda (COP, USD)' },
      { name: 'source_product_id', type: 'varchar(100)', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'ID del producto en sistema origen' },
      { name: 'source_system', type: 'varchar(50)', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Sistema de origen' },
      { name: 'source_table', type: 'varchar(50)', nullable: true, isPrimaryKey: false, isForeignKey: false, description: 'Tabla de origen en sistema legacy' },
      { name: 'source_payload', type: 'jsonb', nullable: true, isPrimaryKey: false, isForeignKey: false, description: 'Payload JSON del sistema origen' },
      { name: 'created_at', type: 'timestamp', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Fecha de creación' },
      { name: 'updated_at', type: 'timestamp', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Fecha de última actualización' },
    ],
    relationships: [
      { targetEntity: 'TENANT', type: 'N:1', foreignKey: 'tenant_id', description: 'Cada producto pertenece a un tenant' },
      { targetEntity: 'PRODUCT_TYPE', type: 'N:1', foreignKey: 'product_type_id', description: 'Cada producto tiene un tipo' },
      { targetEntity: 'BUSINESS_PERSON', type: 'N:1', foreignKey: 'primary_person_id', description: 'Cada producto tiene un titular principal' },
      { targetEntity: 'PRODUCT_HOLDER', type: '1:N', foreignKey: 'product_id', description: 'Un producto puede tener múltiples titulares' },
      { targetEntity: 'BALANCE', type: '1:N', foreignKey: 'product_id', description: 'Un producto puede tener múltiples saldos' },
    ],
    constraints: [
      { type: 'PK', name: 'pk_product', columns: ['id'] },
      { type: 'FK', name: 'fk_product_tenant', columns: ['tenant_id'], definition: 'REFERENCES TENANT(id)' },
      { type: 'FK', name: 'fk_product_type', columns: ['product_type_id'], definition: 'REFERENCES PRODUCT_TYPE(id)' },
      { type: 'FK', name: 'fk_product_person', columns: ['primary_person_id'], definition: 'REFERENCES BUSINESS_PERSON(id)' },
      { type: 'UK', name: 'uk_product_tenant_number', columns: ['tenant_id', 'product_number'] },
      { type: 'CHECK', name: 'chk_product_dates', columns: ['open_date', 'close_date'], definition: 'close_date IS NULL OR close_date >= open_date' },
    ],
  },
  {
    id: 'ENT-005',
    name: 'PRODUCT_HOLDER',
    tableName: 'PRODUCT_HOLDER',
    description: 'Relación entre productos y personas que actúan como titulares, co-titulares, avales o garantes',
    status: 'VALIDADO',
    lastValidated: '2024-06-15T10:50:00Z',
    validatedBy: 'admin@cygnus.com',
    attributes: [
      { name: 'id', type: 'uuid', nullable: false, isPrimaryKey: true, isForeignKey: false, description: 'Identificador único del titular' },
      { name: 'tenant_id', type: 'uuid', nullable: false, isPrimaryKey: false, isForeignKey: true, foreignTable: 'TENANT', description: 'FK al tenant propietario' },
      { name: 'product_id', type: 'uuid', nullable: false, isPrimaryKey: false, isForeignKey: true, foreignTable: 'PRODUCT', description: 'FK al producto' },
      { name: 'person_id', type: 'uuid', nullable: false, isPrimaryKey: false, isForeignKey: true, foreignTable: 'BUSINESS_PERSON', description: 'FK a la persona' },
      { name: 'holder_role', type: 'varchar(20)', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Rol del titular (TITULAR/CO_TITULAR/AVAL/GARANTE/APODERADO)' },
      { name: 'start_date', type: 'date', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Fecha de inicio de la relación' },
      { name: 'end_date', type: 'date', nullable: true, isPrimaryKey: false, isForeignKey: false, description: 'Fecha de fin (null si vigente)' },
      { name: 'created_at', type: 'timestamp', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Fecha de creación' },
      { name: 'updated_at', type: 'timestamp', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Fecha de última actualización' },
    ],
    relationships: [
      { targetEntity: 'TENANT', type: 'N:1', foreignKey: 'tenant_id', description: 'Cada titular pertenece a un tenant' },
      { targetEntity: 'PRODUCT', type: 'N:1', foreignKey: 'product_id', description: 'Cada titular está asociado a un producto' },
      { targetEntity: 'BUSINESS_PERSON', type: 'N:1', foreignKey: 'person_id', description: 'Cada titular es una persona' },
    ],
    constraints: [
      { type: 'PK', name: 'pk_product_holder', columns: ['id'] },
      { type: 'FK', name: 'fk_holder_tenant', columns: ['tenant_id'], definition: 'REFERENCES TENANT(id)' },
      { type: 'FK', name: 'fk_holder_product', columns: ['product_id'], definition: 'REFERENCES PRODUCT(id)' },
      { type: 'FK', name: 'fk_holder_person', columns: ['person_id'], definition: 'REFERENCES BUSINESS_PERSON(id)' },
      { type: 'CHECK', name: 'chk_holder_dates', columns: ['start_date', 'end_date'], definition: 'end_date IS NULL OR end_date >= start_date' },
    ],
  },
  {
    id: 'ENT-006',
    name: 'TRANSACTION_TYPE',
    tableName: 'TRANSACTION_TYPE',
    description: 'Catálogo de tipos de transacción financiera con naturaleza del movimiento (débito/crédito)',
    status: 'VALIDADO',
    lastValidated: '2024-06-15T10:55:00Z',
    validatedBy: 'admin@cygnus.com',
    attributes: [
      { name: 'id', type: 'uuid', nullable: false, isPrimaryKey: true, isForeignKey: false, description: 'Identificador único del tipo de transacción' },
      { name: 'tenant_id', type: 'uuid', nullable: false, isPrimaryKey: false, isForeignKey: true, foreignTable: 'TENANT', description: 'FK al tenant propietario' },
      { name: 'code', type: 'varchar(50)', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Código del tipo de transacción' },
      { name: 'description', type: 'varchar(200)', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Descripción del tipo de transacción' },
      { name: 'movement_nature', type: 'varchar(10)', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Naturaleza del movimiento (DEBITO/CREDITO)' },
      { name: 'source_transaction_type_code', type: 'varchar(50)', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Código en sistema origen' },
      { name: 'created_at', type: 'timestamp', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Fecha de creación' },
      { name: 'updated_at', type: 'timestamp', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Fecha de última actualización' },
    ],
    relationships: [
      { targetEntity: 'TENANT', type: 'N:1', foreignKey: 'tenant_id', description: 'Cada tipo pertenece a un tenant' },
      { targetEntity: 'TRANSACTION_ENTRY', type: '1:N', foreignKey: 'transaction_type_id', description: 'Un tipo puede clasificar múltiples movimientos' },
    ],
    constraints: [
      { type: 'PK', name: 'pk_transaction_type', columns: ['id'] },
      { type: 'FK', name: 'fk_type_tenant', columns: ['tenant_id'], definition: 'REFERENCES TENANT(id)' },
      { type: 'UK', name: 'uk_type_tenant_code', columns: ['tenant_id', 'code'] },
      { type: 'CHECK', name: 'chk_movement_nature', columns: ['movement_nature'], definition: "movement_nature IN ('DEBITO', 'CREDITO')" },
    ],
  },
  {
    id: 'ENT-007',
    name: 'VOUCHER',
    tableName: 'VOUCHER',
    description: 'Comprobantes contables que soportan las transacciones financieras',
    status: 'VALIDADO',
    lastValidated: '2024-06-15T11:00:00Z',
    validatedBy: 'admin@cygnus.com',
    attributes: [
      { name: 'id', type: 'uuid', nullable: false, isPrimaryKey: true, isForeignKey: false, description: 'Identificador único del comprobante' },
      { name: 'tenant_id', type: 'uuid', nullable: false, isPrimaryKey: false, isForeignKey: true, foreignTable: 'TENANT', description: 'FK al tenant propietario' },
      { name: 'voucher_type', type: 'varchar(20)', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Tipo de comprobante (INGRESO/EGRESO/TRASPASO/AJUSTE)' },
      { name: 'voucher_number', type: 'varchar(50)', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Número único del comprobante por tenant' },
      { name: 'voucher_date', type: 'date', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Fecha del comprobante' },
      { name: 'status', type: 'varchar(20)', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Estado (BORRADOR/APROBADO/ANULADO/CONTABILIZADO)' },
      { name: 'source_voucher_id', type: 'varchar(100)', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'ID del comprobante en sistema origen' },
      { name: 'source_system', type: 'varchar(50)', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Sistema de origen' },
      { name: 'source_table', type: 'varchar(50)', nullable: true, isPrimaryKey: false, isForeignKey: false, description: 'Tabla de origen en sistema legacy' },
      { name: 'source_payload', type: 'jsonb', nullable: true, isPrimaryKey: false, isForeignKey: false, description: 'Payload JSON del sistema origen' },
      { name: 'created_at', type: 'timestamp', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Fecha de creación' },
      { name: 'updated_at', type: 'timestamp', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Fecha de última actualización' },
    ],
    relationships: [
      { targetEntity: 'TENANT', type: 'N:1', foreignKey: 'tenant_id', description: 'Cada comprobante pertenece a un tenant' },
      { targetEntity: 'VOUCHER_LINE', type: '1:N', foreignKey: 'voucher_id', description: 'Un comprobante contiene múltiples líneas' },
      { targetEntity: 'TRANSACTION', type: '1:N', foreignKey: 'voucher_id', description: 'Un comprobante puede soportar múltiples transacciones' },
    ],
    constraints: [
      { type: 'PK', name: 'pk_voucher', columns: ['id'] },
      { type: 'FK', name: 'fk_voucher_tenant', columns: ['tenant_id'], definition: 'REFERENCES TENANT(id)' },
      { type: 'UK', name: 'uk_voucher_tenant_type_number', columns: ['tenant_id', 'voucher_type', 'voucher_number'] },
    ],
  },
  {
    id: 'ENT-008',
    name: 'VOUCHER_LINE',
    tableName: 'VOUCHER_LINE',
    description: 'Líneas contables de los comprobantes con montos de débito y crédito',
    status: 'VALIDADO',
    lastValidated: '2024-06-15T11:05:00Z',
    validatedBy: 'admin@cygnus.com',
    attributes: [
      { name: 'id', type: 'uuid', nullable: false, isPrimaryKey: true, isForeignKey: false, description: 'Identificador único de la línea' },
      { name: 'tenant_id', type: 'uuid', nullable: false, isPrimaryKey: false, isForeignKey: true, foreignTable: 'TENANT', description: 'FK al tenant propietario' },
      { name: 'voucher_id', type: 'uuid', nullable: false, isPrimaryKey: false, isForeignKey: true, foreignTable: 'VOUCHER', description: 'FK al comprobante padre' },
      { name: 'line_number', type: 'int', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Número secuencial de la línea' },
      { name: 'account_code', type: 'varchar(50)', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Código de la cuenta contable' },
      { name: 'debit_amount', type: 'decimal(18,2)', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Monto de débito (0 si es crédito)' },
      { name: 'credit_amount', type: 'decimal(18,2)', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Monto de crédito (0 si es débito)' },
      { name: 'created_at', type: 'timestamp', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Fecha de creación' },
      { name: 'updated_at', type: 'timestamp', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Fecha de última actualización' },
    ],
    relationships: [
      { targetEntity: 'TENANT', type: 'N:1', foreignKey: 'tenant_id', description: 'Cada línea pertenece a un tenant' },
      { targetEntity: 'VOUCHER', type: 'N:1', foreignKey: 'voucher_id', description: 'Cada línea pertenece a un comprobante' },
    ],
    constraints: [
      { type: 'PK', name: 'pk_voucher_line', columns: ['id'] },
      { type: 'FK', name: 'fk_line_tenant', columns: ['tenant_id'], definition: 'REFERENCES TENANT(id)' },
      { type: 'FK', name: 'fk_line_voucher', columns: ['voucher_id'], definition: 'REFERENCES VOUCHER(id)' },
      { type: 'CHECK', name: 'chk_line_amounts', columns: ['debit_amount', 'credit_amount'], definition: 'debit_amount >= 0 AND credit_amount >= 0' },
    ],
  },
  {
    id: 'ENT-009',
    name: 'TRANSACTION',
    tableName: 'TRANSACTION',
    description: 'Transacciones financieras que registran operaciones sobre productos, con soporte para reversiones',
    status: 'VALIDADO',
    lastValidated: '2024-06-15T11:10:00Z',
    validatedBy: 'admin@cygnus.com',
    attributes: [
      { name: 'id', type: 'uuid', nullable: false, isPrimaryKey: true, isForeignKey: false, description: 'Identificador único de la transacción' },
      { name: 'tenant_id', type: 'uuid', nullable: false, isPrimaryKey: false, isForeignKey: true, foreignTable: 'TENANT', description: 'FK al tenant propietario' },
      { name: 'voucher_id', type: 'uuid', nullable: false, isPrimaryKey: false, isForeignKey: true, foreignTable: 'VOUCHER', description: 'FK al comprobante asociado' },
      { name: 'operation_number', type: 'varchar(50)', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Número único de operación por tenant' },
      { name: 'transaction_date', type: 'timestamp', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Fecha y hora de la transacción' },
      { name: 'reversal_of_transaction_id', type: 'uuid', nullable: true, isPrimaryKey: false, isForeignKey: true, foreignTable: 'TRANSACTION', description: 'FK a la transacción que se revierte (null si no es reverso)' },
      { name: 'status', type: 'varchar(20)', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Estado (PENDIENTE/COMPLETADA/REVERTIDA/ANULADA)' },
      { name: 'source_operation_id', type: 'varchar(100)', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'ID de operación en sistema origen' },
      { name: 'created_at', type: 'timestamp', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Fecha de creación' },
      { name: 'updated_at', type: 'timestamp', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Fecha de última actualización' },
    ],
    relationships: [
      { targetEntity: 'TENANT', type: 'N:1', foreignKey: 'tenant_id', description: 'Cada transacción pertenece a un tenant' },
      { targetEntity: 'VOUCHER', type: 'N:1', foreignKey: 'voucher_id', description: 'Cada transacción tiene un comprobante' },
      { targetEntity: 'TRANSACTION', type: '1:1', foreignKey: 'reversal_of_transaction_id', description: 'Una transacción puede revertir otra' },
      { targetEntity: 'TRANSACTION_ENTRY', type: '1:N', foreignKey: 'transaction_id', description: 'Una transacción contiene múltiples movimientos' },
    ],
    constraints: [
      { type: 'PK', name: 'pk_transaction', columns: ['id'] },
      { type: 'FK', name: 'fk_trans_tenant', columns: ['tenant_id'], definition: 'REFERENCES TENANT(id)' },
      { type: 'FK', name: 'fk_trans_voucher', columns: ['voucher_id'], definition: 'REFERENCES VOUCHER(id)' },
      { type: 'FK', name: 'fk_trans_reversal', columns: ['reversal_of_transaction_id'], definition: 'REFERENCES TRANSACTION(id)' },
      { type: 'UK', name: 'uk_trans_tenant_operation', columns: ['tenant_id', 'operation_number'] },
    ],
  },
  {
    id: 'ENT-010',
    name: 'TRANSACTION_ENTRY',
    tableName: 'TRANSACTION_ENTRY',
    description: 'Movimientos individuales de cada transacción, con monto y afectación a producto/persona',
    status: 'VALIDADO',
    lastValidated: '2024-06-15T11:15:00Z',
    validatedBy: 'admin@cygnus.com',
    attributes: [
      { name: 'id', type: 'uuid', nullable: false, isPrimaryKey: true, isForeignKey: false, description: 'Identificador único del movimiento' },
      { name: 'tenant_id', type: 'uuid', nullable: false, isPrimaryKey: false, isForeignKey: true, foreignTable: 'TENANT', description: 'FK al tenant propietario' },
      { name: 'transaction_id', type: 'uuid', nullable: false, isPrimaryKey: false, isForeignKey: true, foreignTable: 'TRANSACTION', description: 'FK a la transacción padre' },
      { name: 'transaction_type_id', type: 'uuid', nullable: false, isPrimaryKey: false, isForeignKey: true, foreignTable: 'TRANSACTION_TYPE', description: 'FK al tipo de transacción' },
      { name: 'product_id', type: 'uuid', nullable: true, isPrimaryKey: false, isForeignKey: true, foreignTable: 'PRODUCT', description: 'FK al producto afectado (null si no aplica)' },
      { name: 'person_id', type: 'uuid', nullable: true, isPrimaryKey: false, isForeignKey: true, foreignTable: 'BUSINESS_PERSON', description: 'FK a la persona afectada (null si no aplica)' },
      { name: 'amount', type: 'decimal(18,2)', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Monto del movimiento' },
      { name: 'entry_date', type: 'timestamp', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Fecha del movimiento' },
      { name: 'source_entry_id', type: 'varchar(100)', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'ID del movimiento en sistema origen' },
      { name: 'created_at', type: 'timestamp', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Fecha de creación' },
      { name: 'updated_at', type: 'timestamp', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Fecha de última actualización' },
    ],
    relationships: [
      { targetEntity: 'TENANT', type: 'N:1', foreignKey: 'tenant_id', description: 'Cada movimiento pertenece a un tenant' },
      { targetEntity: 'TRANSACTION', type: 'N:1', foreignKey: 'transaction_id', description: 'Cada movimiento pertenece a una transacción' },
      { targetEntity: 'TRANSACTION_TYPE', type: 'N:1', foreignKey: 'transaction_type_id', description: 'Cada movimiento tiene un tipo' },
      { targetEntity: 'PRODUCT', type: 'N:1', foreignKey: 'product_id', description: 'Cada movimiento puede afectar un producto' },
      { targetEntity: 'BUSINESS_PERSON', type: 'N:1', foreignKey: 'person_id', description: 'Cada movimiento puede afectar una persona' },
    ],
    constraints: [
      { type: 'PK', name: 'pk_transaction_entry', columns: ['id'] },
      { type: 'FK', name: 'fk_entry_tenant', columns: ['tenant_id'], definition: 'REFERENCES TENANT(id)' },
      { type: 'FK', name: 'fk_entry_transaction', columns: ['transaction_id'], definition: 'REFERENCES TRANSACTION(id)' },
      { type: 'FK', name: 'fk_entry_type', columns: ['transaction_type_id'], definition: 'REFERENCES TRANSACTION_TYPE(id)' },
      { type: 'CHECK', name: 'chk_entry_amount', columns: ['amount'], definition: 'amount > 0' },
    ],
  },
  {
    id: 'ENT-011',
    name: 'BALANCE',
    tableName: 'BALANCE',
    description: 'Saldos de los productos financieros por fecha de corte y tipo de saldo',
    status: 'VALIDADO',
    lastValidated: '2024-06-15T11:20:00Z',
    validatedBy: 'admin@cygnus.com',
    attributes: [
      { name: 'id', type: 'uuid', nullable: false, isPrimaryKey: true, isForeignKey: false, description: 'Identificador único del saldo' },
      { name: 'tenant_id', type: 'uuid', nullable: false, isPrimaryKey: false, isForeignKey: true, foreignTable: 'TENANT', description: 'FK al tenant propietario' },
      { name: 'product_id', type: 'uuid', nullable: false, isPrimaryKey: false, isForeignKey: true, foreignTable: 'PRODUCT', description: 'FK al producto' },
      { name: 'balance_date', type: 'date', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Fecha de corte del saldo' },
      { name: 'balance_type', type: 'varchar(20)', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Tipo de saldo (DISPONIBLE/CONTABLE)' },
      { name: 'amount', type: 'decimal(18,2)', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Monto del saldo' },
      { name: 'created_at', type: 'timestamp', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Fecha de creación' },
      { name: 'updated_at', type: 'timestamp', nullable: false, isPrimaryKey: false, isForeignKey: false, description: 'Fecha de última actualización' },
    ],
    relationships: [
      { targetEntity: 'TENANT', type: 'N:1', foreignKey: 'tenant_id', description: 'Cada saldo pertenece a un tenant' },
      { targetEntity: 'PRODUCT', type: 'N:1', foreignKey: 'product_id', description: 'Cada saldo pertenece a un producto' },
    ],
    constraints: [
      { type: 'PK', name: 'pk_balance', columns: ['id'] },
      { type: 'FK', name: 'fk_balance_tenant', columns: ['tenant_id'], definition: 'REFERENCES TENANT(id)' },
      { type: 'FK', name: 'fk_balance_product', columns: ['product_id'], definition: 'REFERENCES PRODUCT(id)' },
      { type: 'UK', name: 'uk_balance_product_date_type', columns: ['product_id', 'balance_date', 'balance_type'] },
    ],
  },
]

// ── Criterios de validación ────────────────────────────────────────────────

export const VALIDATION_CRITERIA: ValidationCriterion[] = [
  { id: 1, name: 'Completitud', description: 'Todas las entidades del modelo E/R están representadas en el paquete', scope: 'ESTRUCTURA', severity: 'CRITICO', isRequired: true },
  { id: 2, name: 'Cardinalidad', description: 'Las relaciones 1:N entre entidades están correctamente definidas', scope: 'ESTRUCTURA', severity: 'ALTO', isRequired: true },
  { id: 3, name: 'Nulabilidad', description: 'Los campos opcionales están correctamente marcados como nullable', scope: 'ESTRUCTURA', severity: 'ALTO', isRequired: true },
  { id: 4, name: 'Unicidad', description: 'Las restricciones UK están definidas según reglas de negocio', scope: 'ESTRUCTURA', severity: 'ALTO', isRequired: true },
  { id: 5, name: 'Trazabilidad', description: 'Los campos source_* están presentes para integración con sistemas legacy', scope: 'DATOS', severity: 'MEDIO', isRequired: true },
  { id: 6, name: 'Aislamiento', description: 'El tenant_id está presente en todas las entidades excepto TENANT', scope: 'DATOS', severity: 'CRITICO', isRequired: true },
  { id: 7, name: 'Normalización', description: 'No existen dependencias transitivas no detectadas (3FN)', scope: 'ESTRUCTURA', severity: 'ALTO', isRequired: true },
  { id: 8, name: 'Tipos de datos', description: 'Los tipos de datos son consistentes y apropiados para cada atributo', scope: 'ESTRUCTURA', severity: 'MEDIO', isRequired: true },
  { id: 9, name: 'Reglas de negocio', description: 'Las restricciones CHECK y reglas de negocio están correctamente implementadas', scope: 'REGLAS', severity: 'CRITICO', isRequired: true },
  { id: 10, name: 'Diagrama', description: 'El diagrama PlantUML refleja fielmente el modelo de datos', scope: 'ESTRUCTURA', severity: 'MEDIO', isRequired: true },
  { id: 11, name: 'Contexto histórico', description: 'Los campos de auditoría (created_at, updated_at, created_by, updated_by) están presentes', scope: 'HISTORICO', severity: 'MEDIO', isRequired: true },
  { id: 12, name: '_PAYLOAD JSON', description: 'Los campos source_payload están presentes para almacenar datos originales', scope: 'HISTORICO', severity: 'BAJO', isRequired: false },
  { id: 13, name: 'Índices', description: 'Los índices necesarios para consultas frecuentes están definidos', scope: 'ESTRUCTURA', severity: 'BAJO', isRequired: false },
  { id: 14, name: 'Particionamiento', description: 'Se ha evaluado la necesidad de particionamiento para tablas grandes', scope: 'DATOS', severity: 'BAJO', isRequired: false },
  { id: 15, name: 'Integración Transversales', description: 'Los contratos de integración con servicios transversales están definidos', scope: 'INTEGRIDAD', severity: 'MEDIO', isRequired: true },
]

// ── Historial de cambios ────────────────────────────────────────────────────

export const HISTORICAL_RECORDS: HistoricalRecord[] = [
  {
    id: 'HIST-001',
    entityId: 'ENT-001',
    action: 'CREACION',
    timestamp: '2024-01-15T08:00:00Z',
    userId: 'USR-001',
    userName: 'Carlos Mendoza',
    details: 'Creación inicial de la entidad TENANT en el modelo canónico',
  },
  {
    id: 'HIST-002',
    entityId: 'ENT-002',
    action: 'CREACION',
    timestamp: '2024-01-15T08:30:00Z',
    userId: 'USR-001',
    userName: 'Carlos Mendoza',
    details: 'Creación de la entidad BUSINESS_PERSON con campos de trazabilidad',
  },
  {
    id: 'HIST-003',
    entityId: 'ENT-002',
    action: 'MODIFICACION',
    timestamp: '2024-02-20T14:15:00Z',
    userId: 'USR-002',
    userName: 'Ana García',
    details: 'Se agregó el campo source_payload para almacenar datos JSON del sistema origen',
    previousValues: { attributes: 14 },
    newValues: { attributes: 15 },
  },
  {
    id: 'HIST-004',
    entityId: 'ENT-004',
    action: 'CREACION',
    timestamp: '2024-01-20T10:00:00Z',
    userId: 'USR-001',
    userName: 'Carlos Mendoza',
    details: 'Creación de la entidad PRODUCT con relación a PRODUCT_TYPE y BUSINESS_PERSON',
  },
  {
    id: 'HIST-005',
    entityId: 'ENT-004',
    action: 'VALIDACION',
    timestamp: '2024-03-10T16:45:00Z',
    userId: 'USR-003',
    userName: 'Roberto López',
    details: 'Validación exitosa de la entidad PRODUCT contra especificación CACSA',
  },
  {
    id: 'HIST-006',
    entityId: 'ENT-009',
    action: 'CREACION',
    timestamp: '2024-02-01T09:00:00Z',
    userId: 'USR-001',
    userName: 'Carlos Mendoza',
    details: 'Creación de la entidad TRANSACTION con soporte para reversiones',
  },
  {
    id: 'HIST-007',
    entityId: 'ENT-009',
    action: 'MODIFICACION',
    timestamp: '2024-03-15T11:30:00Z',
    userId: 'USR-002',
    userName: 'Ana García',
    details: 'Se agregó la restricción de reversión ciclica para evitar bucles infinitos',
    previousValues: { constraints: 3 },
    newValues: { constraints: 4 },
  },
  {
    id: 'HIST-008',
    entityId: 'ENT-010',
    action: 'CREACION',
    timestamp: '2024-02-01T09:30:00Z',
    userId: 'USR-001',
    userName: 'Carlos Mendoza',
    details: 'Creación de la entidad TRANSACTION_ENTRY con exclusión mutua product_id/person_id',
  },
  {
    id: 'HIST-009',
    entityId: 'ENT-010',
    action: 'VALIDACION',
    timestamp: '2024-04-05T10:20:00Z',
    userId: 'USR-003',
    userName: 'Roberto López',
    details: 'Validación de la regla de negocio: product_id y person_id mutuamente excluyentes',
  },
  {
    id: 'HIST-010',
    entityId: 'ENT-011',
    action: 'CREACION',
    timestamp: '2024-02-05T14:00:00Z',
    userId: 'USR-001',
    userName: 'Carlos Mendoza',
    details: 'Creación de la entidad BALANCE con tipos DISPONIBLE y CONTABLE',
  },
  {
    id: 'HIST-011',
    entityId: 'ENT-001',
    action: 'APROBACION',
    timestamp: '2024-05-01T09:00:00Z',
    userId: 'USR-004',
    userName: 'María Fernández',
    details: 'Aprobación del modelo completo por el Arquitecto de Datos',
  },
  {
    id: 'HIST-012',
    entityId: 'ENT-007',
    action: 'MODIFICACION',
    timestamp: '2024-05-15T15:30:00Z',
    userId: 'USR-002',
    userName: 'Ana García',
    details: 'Se agregaron campos de trazabilidad source_table y source_payload al VOUCHER',
    previousValues: { attributes: 9 },
    newValues: { attributes: 12 },
  },
]

// ── Versiones del paquete ──────────────────────────────────────────────────

export const SPECIFICATION_VERSIONS: SpecificationVersion[] = [
  {
    version: '1.0.0',
    date: '2024-01-15',
    author: 'Carlos Mendoza',
    changes: ['Creación inicial del modelo canónico CACSA', '11 entidades definidas', 'Relaciones 1:N establecidas'],
    status: 'VALIDADO',
  },
  {
    version: '1.1.0',
    date: '2024-02-20',
    author: 'Ana García',
    changes: ['Agregado source_payload a BUSINESS_PERSON', 'Agregados campos de auditoría created_by/updated_by'],
    status: 'VALIDADO',
  },
  {
    version: '1.2.0',
    date: '2024-03-15',
    author: 'Carlos Mendoza',
    changes: ['Restricción de reversión ciclica en TRANSACTION', 'CHECK para montos no negativos en VOUCHER_LINE'],
    status: 'VALIDADO',
  },
  {
    version: '2.0.0',
    date: '2024-05-01',
    author: 'María Fernández',
    changes: ['Aprobación completa del modelo', 'Documentación de todas las entidades', 'Definición de 15 criterios de validación'],
    status: 'VALIDADO',
  },
  {
    version: '2.1.0',
    date: '2024-06-15',
    author: 'Roberto López',
    changes: ['Validación contra especificación CACSA', 'Generación de reporte de cumplimiento', 'Agregado contexto histórico rico'],
    status: 'VALIDADO',
  },
]

// ── Resultados de validación ────────────────────────────────────────────────

export const VALIDATION_RESULTS: ValidationResult[] = [
  { criterionId: 1, passed: true, severity: 'CRITICO', message: 'Todas las 11 entidades están representadas', details: ['TENANT ✓', 'BUSINESS_PERSON ✓', 'PRODUCT_TYPE ✓', 'PRODUCT ✓', 'PRODUCT_HOLDER ✓', 'TRANSACTION_TYPE ✓', 'VOUCHER ✓', 'VOUCHER_LINE ✓', 'TRANSACTION ✓', 'TRANSACTION_ENTRY ✓', 'BALANCE ✓'], timestamp: '2024-06-15T10:30:00Z' },
  { criterionId: 2, passed: true, severity: 'ALTO', message: 'Relaciones 1:N correctamente definidas', details: ['TENANT → BUSINESS_PERSON ✓', 'TENANT → PRODUCT_TYPE ✓', 'PRODUCT_TYPE → PRODUCT ✓', 'BUSINESS_PERSON → PRODUCT ✓', 'PRODUCT → PRODUCT_HOLDER ✓', 'VOUCHER → VOUCHER_LINE ✓', 'VOUCHER → TRANSACTION ✓', 'TRANSACTION → TRANSACTION_ENTRY ✓'], timestamp: '2024-06-15T10:35:00Z' },
  { criterionId: 3, passed: true, severity: 'ALTO', message: 'Campos nullable correctamente marcados', details: ['PRODUCT.close_date ✓', 'PRODUCT_HOLDER.end_date ✓', 'TRANSACTION.reversal_of_transaction_id ✓', 'TRANSACTION_ENTRY.product_id ✓', 'TRANSACTION_ENTRY.person_id ✓'], timestamp: '2024-06-15T10:40:00Z' },
  { criterionId: 4, passed: true, severity: 'ALTO', message: 'Restricciones UK definidas', details: ['TENANT.code ✓', 'BUSINESS_PERSON.tenant_id+identification_number ✓', 'PRODUCT.tenant_id+product_number ✓', 'VOUCHER.tenant_id+voucher_type+voucher_number ✓', 'TRANSACTION.tenant_id+operation_number ✓'], timestamp: '2024-06-15T10:45:00Z' },
  { criterionId: 5, passed: true, severity: 'MEDIO', message: 'Campos de trazabilidad presentes', details: ['BUSINESS_PERSON.source_system ✓', 'BUSINESS_PERSON.source_person_code ✓', 'PRODUCT.source_product_id ✓', 'TRANSACTION.source_operation_id ✓', 'TRANSACTION_ENTRY.source_entry_id ✓'], timestamp: '2024-06-15T10:50:00Z' },
  { criterionId: 6, passed: true, severity: 'CRITICO', message: 'Aislamiento por tenant implementado', details: ['TENANT (excluida) ✓', 'BUSINESS_PERSON.tenant_id ✓', 'PRODUCT_TYPE.tenant_id ✓', 'PRODUCT.tenant_id ✓', 'PRODUCT_HOLDER.tenant_id ✓', 'TRANSACTION_TYPE.tenant_id ✓', 'VOUCHER.tenant_id ✓', 'VOUCHER_LINE.tenant_id ✓', 'TRANSACTION.tenant_id ✓', 'TRANSACTION_ENTRY.tenant_id ✓', 'BALANCE.tenant_id ✓'], timestamp: '2024-06-15T10:55:00Z' },
  { criterionId: 7, passed: true, severity: 'ALTO', message: 'Normalización 3FN verificada', details: ['Sin dependencias transitivas detectadas', 'Cada campo depende solo de la PK', 'Las FK referencian entidades únicas'], timestamp: '2024-06-15T11:00:00Z' },
  { criterionId: 8, passed: true, severity: 'MEDIO', message: 'Tipos de datos consistentes', details: ['uuid para PKs y FKs', 'varchar para textos', 'decimal(18,2) para montos', 'timestamp para fechas', 'jsonb para payloads'], timestamp: '2024-06-15T11:05:00Z' },
  { criterionId: 9, passed: true, severity: 'CRITICO', message: 'Reglas de negocio implementadas', details: ['CHECK balances de comprobantes ✓', 'CHECK fechas consistentes ✓', 'CHECK roles de titular válidos ✓', 'CHECK reversión a transacción existente ✓', 'CHECK integridad referencial ✓'], timestamp: '2024-06-15T11:10:00Z' },
  { criterionId: 10, passed: true, severity: 'MEDIO', message: 'Diagrama PlantUML fiel al modelo', details: ['11 entidades documentadas', 'Relaciones reflejadas', 'Cardinalidades correctas'], timestamp: '2024-06-15T11:15:00Z' },
  { criterionId: 11, passed: true, severity: 'MEDIO', message: 'Contexto histórico completo', details: ['created_at en todas las entidades ✓', 'updated_at en todas las entidades ✓', 'created_by en BUSINESS_PERSON ✓', 'updated_by en BUSINESS_PERSON ✓', 'source_payload para datos originales ✓'], timestamp: '2024-06-15T11:20:00Z' },
  { criterionId: 12, passed: true, severity: 'BAJO', message: 'Campos source_payload presentes', details: ['BUSINESS_PERSON.source_payload ✓', 'PRODUCT.source_payload ✓', 'VOUCHER.source_payload ✓'], timestamp: '2024-06-15T11:25:00Z' },
  { criterionId: 13, passed: false, severity: 'BAJO', message: 'Índices pendientes de definición', details: ['Faltan índices por fecha para consultas frecuentes', 'Faltan índices por estado para filtrado'], timestamp: '2024-06-15T11:30:00Z' },
  { criterionId: 14, passed: false, severity: 'BAJO', message: 'Particionamiento no evaluado', details: ['TRANSACTION podría requerir particionamiento por fecha', 'BALANCE podría requerir particionamiento por tenant'], timestamp: '2024-06-15T11:35:00Z' },
  { criterionId: 15, passed: true, severity: 'MEDIO', message: 'Integración Transversales definida', details: ['Contratos de auditoría ✓', 'Servicios de seguridad ✓', 'API de reportes ✓'], timestamp: '2024-06-15T11:40:00Z' },
]

// ── Paquete de especificación completo ─────────────────────────────────────

export const SPECIFICATION_PACKAGE: SpecificationPackage = {
  id: 'PKG-001',
  name: 'Modelo Canónico Transversal CACSA',
  version: '2.1.0',
  description: 'Paquete de especificación completo para el modelo E/R canónico de integración CACSA-Transversales',
  entities: SPECIFICATION_ENTITIES,
  criteria: VALIDATION_CRITERIA,
  results: VALIDATION_RESULTS,
  history: HISTORICAL_RECORDS,
  versions: SPECIFICATION_VERSIONS,
  createdAt: '2024-01-15T08:00:00Z',
  updatedAt: '2024-06-15T11:40:00Z',
  createdBy: 'Carlos Mendoza',
  status: 'VALIDADO',
}
